# Generated by Django 3.2.5 on 2022-02-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=10000)),
                ('short_url', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
